# Code generated by UI_elements(), Tue Apr 11 13:01:12 2023
# to be sourced into app_ui.R:

fluidPage(
  # Customize this header later
  shinyjs::useShinyjs(),
  shinyFeedback::useShinyFeedback(),
  h1("MancRiskScreenUI"),
  textOutput("intro_text"),


  h2("Simulation parameters"),
  fluidRow(
    column(width=NCOL, numericInput("inum", "Number of simulated women", value = 1e+05) ),
   # Not used - not functional in the model but removing causes issues
    column(width=NCOL, textInput("jnum","Number of simulated lifetimes per woman") )
  ),
  h2("Screening programme and related parameters"),
  fluidRow(
   # GAM model runs for all (6) base strategies
   # UNKNOWN: NA
    column(width=NCOL, checkboxInput("supplemental_screening","When switched on adds MRI and ultrasound screening for women with dense breasts", value = 0) ),
    column(width=NCOL, sliderInput("uptakefirstscreen", "Probability that woman attends first screening", step = 0.01, value = 0.6, min = 0, max = 1) ),
    column(width=NCOL, sliderInput("uptakeotherscreen", "Probability that woman attends further screening (having attended first)", step = 0.01, value = 0.85, min = 0, max = 1) ),
    column(width=NCOL, sliderInput("uptakenoscreen", "Probability that woman attends screening (having missed first)", step = 0.01, value = 0.19, min = 0, max = 0.8) ),
    column(width=NCOL, sliderInput("risk_uptake", "Proportion of women who want risk predicted", step = 0.01, value = 1, min = 0, max = 1) ),
    column(width=NCOL, sliderInput("risk_feedback", "Proportion of women who attend risk consultation", step = 0.01, value = 1, min = 0, max = 1) ),
    column(width=NCOL, sliderInput("screen_change", "Proportion of women with high/moderate/low risk who change screening interval", step = 0.01, value = 1, min = 0, max = 1) ),
   # Values below 24 may produce misleading results as tumours don't have enough time to develop correctly
    column(width=NCOL, sliderInput("start_age", "Age of an individual at start of simulation", step = 1, value = 38, min = 18, max = 60) ),
   # This can be fixed as there are some hard checks in the model
    column(width=NCOL, numericInput("time_horizon", "Max age in the model (100)", value = 100, min = 100) ),
    column(width=NCOL, sliderInput("discount_health", "Health discount rate", step = 0.005, value = 0.035, min = 0, max = 0.1) ),
    column(width=NCOL, sliderInput("discount_cost", "Cost discount rate", step = 0.005, value = 0.035, min = 0, max = 0.1) )
  ),
  h2("Clinical parameters for screening"),
  fluidRow(
    column(width=NCOL, sliderInput("prop_screen_detected", "Proportion of cancers in screening age range detected by screen", step = 0.01, value = 0.43, min = 0, max = 0.6) ),
    column(width=NCOL, numericInput("acmmortality_wb_a", "All-cause mortality Weibull shape", value = 7.937) ),
    column(width=NCOL, numericInput("acmmortality_wb_b", "All-cause mortality Weibull scale", value = 86.79) ),
   # Must be decreasing, adjust units (5-yr to rate param)
    column(width=NCOL, sliderInput("gamma_survival_1", "Five-year survival for stage 1 cancer", step = 0.01, value = 0.98, min = 0, max = 1) ),
    column(width=NCOL, sliderInput("gamma_survival_2", "Five-year survival for stage 2 cancer", step = 0.01, value = 0.9, min = 0, max = 1) ),
    column(width=NCOL, sliderInput("gamma_survival_3", "Five-year survival for stage 3 cancer", step = 0.01, value = 0.72, min = 0, max = 1) ),
   # Must sum to 1
    column(width=NCOL, textInput("Incidence_Mortality","Incidence disribution") ),
   # Fixed
    column(width=NCOL, textInput("risk_mat","Synthetic dataset of breast density, 10 year, and lifetime breast cancer risk derived from PROCAS2 study") ),
    column(width=NCOL, shinyMatrix::matrixInput("metastatic_prob", value = data.matrix(data.frame(age=c(25,35,45,55,65,75,85), prob=c(0.046218154,0.086659039,0.109768116,0.127099924,0.142505975,0.159837783,1.73E-01)),rownames.force=F),
rows = list(names = F, editableNames = F),
cols = list(names = T, editableNames = F),
class = "numeric") ),
   # This is quite an important one but there is quite complex calculation underpinning it that might need people to send me data to reformat
    column(width=NCOL, shinyMatrix::matrixInput("stage_by_size_mat", value = data.matrix(data.frame(v1=c(0.383,0.567,0.611,0.557,0,0), v2=c(0.033,0.111,0.180,0.208,0.723,0.563), v3=c(0.058,0.057,0.208,0.147,0.206,0.351), v5=c(0.525,0.265,0.120,0.088,0.071,0.086)),rownames.force=F),
rows = list(names = F, editableNames = F),
cols = list(names = T, editableNames = F),
class = "numeric") ),
    column(width=NCOL, numericInput("screen_detection_m", "Mean doubling rate for tumours at screen detection", value = 6.12) ),
    column(width=NCOL, numericInput("screen_detection_sd", "Standard deviation of the doubling rate for tumours at screen detection", value = 0.96) ),
    column(width=NCOL, numericInput("clin_detection_m", "Mean doubling rate for tumours", value = 6.5) ),
    column(width=NCOL, numericInput("clin_detection_sd", "Standard deviation of the doubling rate for tumours", value = 0.535) ),
    column(width=NCOL, numericInput("beta_1", "Sensitivity of mammography (β₁) — how rapidly sensitivity changes with tumour size", value = 1.47) ),
    column(width=NCOL, numericInput("beta_2", "Sensitivity of mammography (β₂) — size of tumour for which sensitivity is equal to 50%.", value = 6.51) ),
   # Fixed
    column(width=NCOL, numericInput("sensitivity_max", "Maximum screening sensitivity", value = 0.95, min = 0, max = 1) ),
   # Sen_VDG must be decreasing, and less than sensitivity_max
    column(width=NCOL, sliderInput("VDG1_sen", "Sensitivity of mammography for Volpara Density Group (VDG) 1.", step = 0.01, value = 0.85, min = 0, max = 1) ),
    column(width=NCOL, sliderInput("VDG2_sen", "Sensitivity of mammography for Volpara Density Group (VDG) 2.", step = 0.01, value = 0.78, min = 0, max = 1) ),
    column(width=NCOL, sliderInput("VDG3_sen", "Sensitivity of mammography for Volpara Density Group (VDG) 3.", step = 0.01, value = 0.7, min = 0, max = 1) ),
    column(width=NCOL, sliderInput("VDG4_sen", "Sensitivity of mammography for Volpara Density Group (VDG) 4.", step = 0.01, value = 0.61, min = 0, max = 1) ),
    column(width=NCOL, numericInput("Sen_VDG_av", "Average mammography sensitivity", value = 0.757) ),
    column(width=NCOL, numericInput("Mammo_cdr", "Cancer detection rate per 1000 high dense screens Mammo CEPAC", value = 4.2) ),
    column(width=NCOL, sliderInput("MRI_cdr", "CDR for MRI in Mammo negative women (incremental)", step = 0.01, value = 0, min = 0, max = 1) ),
    column(width=NCOL, sliderInput("US_cdr", "CDR for US in Mammo negative women (incremental)", step = 0.01, value = 0, min = 0, max = 1) ),
    column(width=NCOL, numericInput("log_norm_mean", "Tumour growth rate mean (lognormal)", value = 1.07) ),
    column(width=NCOL, numericInput("log_norm_sd", "Tumour growth rate SD", value = 1.31) ),
   # Fixed
    column(width=NCOL, numericInput("max_size", "Maximum tumour size", value = 128) ),
   # Fixed
    column(width=NCOL, numericInput("start_size", "Tumour starting size (diameter)", value = 0.25) ),
   # Must be decreasing, adjust units  (5-yr to rate param)
    column(width=NCOL, sliderInput("meta_survival_54", "Five-year metatstatic survival, ages 0-54", step = 0.01, value = 0.43, min = 0, max = 1) ),
    column(width=NCOL, sliderInput("meta_survival_74", "Five-year metastatic survival, ages 55-74", step = 0.01, value = 0.29, min = 0, max = 1) ),
    column(width=NCOL, sliderInput("meta_survival_99", "Five-year metastatic survival, ages 75+", step = 0.01, value = 0.16, min = 0, max = 1) ),
    column(width=NCOL, sliderInput("screen_startage", "Screen start age", value = 50, min = 18, max = 60) ),
    column(width=NCOL, sliderInput("screen_endage", "Screen end age", value = 70, min = 18, max = 90) ),
   # UNKNOWN: NA
   # UNKNOWN: NA
    column(width=NCOL, numericInput("low_risk_cut", "Risk cut-off in low-risk-only strategies", value = 1.5) ),
    column(width=NCOL, numericInput("density_cutoff", "Breast density cut-offs for supplemental sreening (VDG groups 3 and 4)", value = 3, min = 1, max = 4) )
   # UNKNOWN: NA
  ),
  h2("Cost data"),
  fluidRow(
    column(width=NCOL, numericInput("cost_strat", "Cost of stratification process", value = 8.45, min = 0, max = 200) ),
    column(width=NCOL, numericInput("cost_screen", "Cost of screening", value = 60.56, min = 0, max = 200) ),
    column(width=NCOL, numericInput("cost_follow_up", "Cost of follow up", value = 106) ),
    column(width=NCOL, numericInput("cost_biop", "Cost of biopsy", value = 290) ),
    column(width=NCOL, numericInput("cost_DCIS", "Cost of DCIS screening?", value = 9840, min = 0, max = 50000) ),
    column(width=NCOL, numericInput("cost_US", "Cost of ultrasonography", value = 52) ),
    column(width=NCOL, numericInput("cost_MRI", "Cost of MRI", value = 114) ),
   # Fixed (for now), to be simplified / tuned by simpler parameter set in the future
    column(width=NCOL, shinyMatrix::matrixInput("tblLookup", value = data.matrix(costs_laudicella(),rownames.force=F),
rows = list(names = F, editableNames = F),
cols = list(names = T, editableNames = F),
class = "numeric") )
  ),
  h2("False Positive and Overdiagnosis parameters"),
  fluidRow(
    column(width=NCOL, numericInput("recall_rate", "Approx. UK recall rate", step = 0.01, value = 0.05, min = 0, max = 1) ),
    column(width=NCOL, numericInput("biopsy_rate", "False-positivebiopsyproportion", step = 0.01, value = 0.02, min = 0, max = 1) )
  ),
  h2("Utility Weights"),
  fluidRow(
    column(width=NCOL, shinyMatrix::matrixInput("utility_ages", value = data.matrix(data.frame(age=c(30,35,40,45,50,55,60,65,70,75,80,85,90,95,100), util=c(0.9383,0.9145,0.9069,0.8824,0.8639,0.8344,0.8222,0.8072,0.8041,0.779,0.7533,0.6985,0.6497,0.6497,0.6497)),rownames.force=F),
rows = list(names = F, editableNames = F),
cols = list(names = T, editableNames = F),
class = "numeric") ),
    column(width=NCOL, numericInput("utility_DCIS", "Non/micro-invasive tumour (DCIS) utility decrement", step = 0.01, value = 1, min = 0, max = 1) ),
    column(width=NCOL, numericInput("util_1to3", "Utility decrement (first yeara, set time independent) stages 1 to 3", step = 0.01, value = 0.82, min = 0, max = 1) ),
    column(width=NCOL, numericInput("util_4", "Utility decrement (first year, set time independent) metastatic", step = 0.01, value = 0.75, min = 0, max = 1) ),
    column(width=NCOL, textInput("utility_stage_cat_y1","First year utility decrements (set time independent)") ),
    column(width=NCOL, textInput("utility_stage_cat_follow","Following year utility decrements (set time independent)") )
  ),
  h2("Output"),
  fluidRow(
    column(width=NCOL, textInput("results","") ),
    column(width=NCOL, textInput("merged_result","") )
  ),


  # Customize this closure later
  h3("Status"),
  verbatimTextOutput("status"),

  p("This is still just a random plot:"),
  plotOutput("plot")
)
