# Code generated by UI_elements(), Mon Mar 27 11:52:56 2023
# to be sourced into app_ui.R:

fluidPage(
  # Customize this header later
  shinyjs::useShinyjs(),
  h1("MancRiskScreenUI"),
  tableOutput("text"),


  h2("Simulation parameters"),
  fluidRow(
    column(width=NCOL, numericInput("inum", "Number of cases?", value = 1e+05) )
   # Not used
   # jnum, ?, batch size?, Not used
   # 
  ),
  h2("Screening programme and related parameters"),
  fluidRow(
   # GAM model runs for all (6) base strategies
    column(width=NCOL, numericInput("screen_strategy", "Screening strategy", value = 2) ),
   # supplemental_screening, check, 0
    column(width=NCOL, numericInput("uptakefirstscreen", "Probability that woman attends first screening", value = 0.605) ),
    column(width=NCOL, numericInput("uptakeotherscreen", "Probability that woman attends further screening (having attended first)", value = 0.852) ),
    column(width=NCOL, numericInput("uptakenoscreen", "Probability that woman attends screening (having missed first)", value = 0.191) ),
    column(width=NCOL, numericInput("risk_uptake", "Proportion of women who want risk predicted", value = 1) ),
    column(width=NCOL, numericInput("risk_feedback", "Proportion of women who attend risk consultation", value = 1) ),
    column(width=NCOL, numericInput("screen_change", "Proportion of women with high/moderate/low risk who change screening interval", value = 1) ),
    column(width=NCOL, numericInput("start_age", "Age of an individual at start of simulation", value = 38) ),
   # time_horizon, 100, 90-120, years
    column(width=NCOL, numericInput("discount_health", "Health discount rate", value = 0.035) ),
    column(width=NCOL, numericInput("discount_cost", "Cost discount rate", value = 0.035) )
   # 
  ),
  h2("Clinical parameters for screening"),
  fluidRow(
    column(width=NCOL, numericInput("prop_screen_detected", "Proportion of cancers in screening age range detected by screen", value = 0.431) ),
    column(width=NCOL, numericInput("acmmortality_wb_a", "All-cause mortality Weibull shape", value = 7.937) ),
    column(width=NCOL, numericInput("acmmortality_wb_b", "All-cause mortality Weibull scale", value = 86.788) ),
   # Must be decreasing, adjust units (5-yr to rate param)
    column(width=NCOL, numericInput("gamma_survival_1", "Five-year survival for stage 1 cancer", value = 0.979, min = 0, max = 1) ),
    column(width=NCOL, numericInput("gamma_survival_2", "Five-year survival for stage 2 cancer", value = 0.896, min = 0, max = 1) ),
    column(width=NCOL, numericInput("gamma_survival_3", "Five-year survival for stage 3 cancer", value = 0.72, min = 0, max = 1) ),
   # 
   # 
   # Incidence_Mortality, table, Incidence disribution
   # Fixed
   # risk_mat, file, Synthetic dataset of breast density, 10 year, and lifetime breast cancer risk derived from PROCAS2 study, Fixed
   # metastatic_prob, table, Metastatic cancer probabilities by age
   # stage_by_size_mat, table, Nottingham Prognostic Indicator by cancer size
    column(width=NCOL, numericInput("screen_detection_m", "Mean doubling rate for tumours at screen detection", value = 6.12) ),
    column(width=NCOL, numericInput("screen_detection_sd", "Standard deviation of the doubling rate for tumours at screen detection", value = 0.96) ),
    column(width=NCOL, numericInput("clin_detection_m", "Mean doubling rate for tumours", value = 6.5) ),
    column(width=NCOL, numericInput("clin_detection_sd", "Standard deviation of the doubling rate for tumours", value = 0.535) ),
    column(width=NCOL, numericInput("beta1", "Sensitivity of mammography (β₁) — how rapidly sensitivity changes with tumour size", value = 1.47) ),
    column(width=NCOL, numericInput("beta2", "Sensitivity of mammography (β₂) — size of tumour for which sensitivity is equal to 50%.", value = 6.51) ),
    column(width=NCOL, numericInput("sensitivity_max", "Maximum screening sensitivity", value = 0.95) ),
   # Sen_VDG must be decreasing, and less than sensitivity_max
    column(width=NCOL, numericInput("Sen_VDG[1]", "Sensitivity of mammography for Volpara Density Group (VDG) 1.", value = 0.85, min = 0, max = 1) ),
    column(width=NCOL, numericInput("Sen_VDG[2]", "Sensitivity of mammography for Volpara Density Group (VDG) 2.", value = 0.776, min = 0, max = 1) ),
    column(width=NCOL, numericInput("Sen_VDG[3]", "Sensitivity of mammography for Volpara Density Group (VDG) 3.", value = 0.695, min = 0, max = 1) ),
    column(width=NCOL, numericInput("Sen_VDG[4]", "Sensitivity of mammography for Volpara Density Group (VDG) 4.", value = 0.61, min = 0, max = 1) ),
    column(width=NCOL, numericInput("Sen_VDG_av", "Average mammography sensitivity", value = 0.757) ),
    column(width=NCOL, numericInput("Mammo_cdr", "Cancer detection rate per 1000 high dense screens Mammo CEPAC", value = 4.2) ),
    column(width=NCOL, numericInput("MRI_cdr", "CDR for MRI in Mammo negative women (incremental)", value = 0.005, min = 0, max = 1) ),
    column(width=NCOL, numericInput("US_cdr", "CDR for US in Mammo negative women (incremental)", value = 0.003, min = 0, max = 1) ),
    column(width=NCOL, numericInput("log_norm_mean", "Tumour growth rate mean (lognormal)", value = 1.07) ),
    column(width=NCOL, numericInput("log_norm_sd", "Tumour growth rate SD", value = 1.31) ),
    column(width=NCOL, numericInput("max_size", "Maximum tumour size", value = 128) ),
    column(width=NCOL, numericInput("start_size", "Tumour starting size (diameter)", value = 0.25) ),
   # Must be decreasing, adjust units  (5-yr to rate param)
    column(width=NCOL, numericInput("meta_survival_54", "Five-year metatstatic survival, ages 0-54", value = 0.433, min = 0, max = 1) ),
    column(width=NCOL, numericInput("meta_survival_74", "Five-year metastatic survival, ages 55-74", value = 0.287, min = 0, max = 1) ),
    column(width=NCOL, numericInput("meta_survival_99", "Five-year metastatic survival, ages 75+", value = 0.162, min = 0, max = 1) ),
   # 
   # screen_startage, 50, start_age - time_horizon, years
   # screen_endage, 70, start_age - time_horizon, years
   # 
   # risk_cutoffs_procas, vector, Risk cut-offs for PROCAS plan
   # risk_cutoffs_tert, vector, Risk cut-offs for tertiles of risk
    column(width=NCOL, numericInput("low_risk_cut", "Risk cut-off in low-risk-only strategies", value = 1.5) ),
    column(width=NCOL, numericInput("density_cutoff", "Breast density cut-offs for supplemental sreening (VDG groups 3 and 4)", value = 3) )
   # ca_size_cut, vector, Cancer size category cut-points (from Kolias 1999)
   # 
  ),
  h2("Cost data"),
  fluidRow(
    column(width=NCOL, numericInput("cost_strat", "Cost of stratification process", value = 8.45) ),
    column(width=NCOL, numericInput("cost_screen", "Cost of screening", value = 60.56) ),
    column(width=NCOL, numericInput("cost_follow_up", "Cost of follow up", value = 106) ),
    column(width=NCOL, numericInput("cost_biop", "Cost of biopsy", value = 290) ),
    column(width=NCOL, numericInput("cost_DCIS", "Cost of DCIS screening?", value = 9840) ),
    column(width=NCOL, numericInput("cost_US", "Cost of ultrasonography", value = 52) ),
    column(width=NCOL, numericInput("cost_MRI", "Cost of MRI", value = 114) )
   # Fixed (for now), to be simplified / tuned by simpler parameter set in the future
   # tbl, table, Cost of cancer treatment, Fixed (for now), to be simplified / tuned by simpler parameter set in the future
   # 
   # 
  ),
  h2("False Positive and Overdiagnosis parameters"),
  fluidRow(
    column(width=NCOL, numericInput("recall_rate", "Approx. UK recall rate", value = 0.0456) ),
    column(width=NCOL, numericInput("biopsy_rate", "False-positivebiopsyproportion", value = 0.024) )
   # 
  ),
  h2("Utility Weights"),
  fluidRow(
   # utility_ages, table, Set age adjusted utility values
    column(width=NCOL, numericInput("utility_DCIS", "Non/micro-invasive tumour (DCIS) utility decrement", value = 1) ),
   # utility_stage_cat_y1, table, First year utility decrements (set time independent)
    column(width=NCOL, numericInput("util_1to3", "Utility decrement (first yeara, set time independent) stages 1 to 3", value = 0.82, min = 0, max = 1) ),
    column(width=NCOL, numericInput("util_4", "Utility decrement (first year, set time independent) metastatic", value = 0.75, min = 0, max = 1) )
   # 
   # utility_stage_cat_follow, table, Following year utility decrements (set time independent)
   # 
  ),
  h2("Output"),
   # results
   # merged_result


  # Customize this closure later
  p("This is still just a random plot:"),
  plotOutput("plot")
)
