# Code generated by UI_elements(), Mon Mar 27 11:52:56 2023
# to be sourced into app_server.R:

advanced_inputs <- c("inum", "screen_strategy", "uptakefirstscreen", "uptakeotherscreen", "uptakenoscreen", "risk_uptake", "risk_feedback", "screen_change", "start_age", "discount_health", "discount_cost", "prop_screen_detected", "acmmortality_wb_a", "acmmortality_wb_b", "screen_detection_m", "screen_detection_sd", "clin_detection_m", "clin_detection_sd", "sensitivity_max", "Sen_VDG_av", "Mammo_cdr", "max_size", "start_size", "low_risk_cut", "density_cutoff", "cost_strat", "cost_screen", "cost_follow_up", "cost_biop", "cost_DCIS", "cost_US", "cost_MRI", "recall_rate", "biopsy_rate", "utility_DCIS")
