# Code generated by parse_ui_table.R, Thu Jun 15 13:57:56 2023
# Edit input config in: data_raw/input_config.csv:
# Edit parsing rules & layout in: data_raw/parse_ui_table.R
auto_generated_ui <- function(...) {

  tabsetPanel( ... ,
    tabPanel(title = "Simulation",
      h3("Simulation parameters"),
      numericInput("inum", "Number of simulated women", value = 1e+05),
      # Not used - not functional in the model but removing causes issues
      textInput("jnum","Number of simulated lifetimes per woman")
    ),
    tabPanel(title = "Strategy",
      h3("Screening programme and related parameters"),
      # GAM model runs for all (6) base strategies
      # UNKNOWN: NA
      checkboxInput("supplemental_screening","When switched on adds MRI and ultrasound screening for women with dense breasts", value = 0),
      # Values below 24 may produce misleading results as tumours don't have enough time to develop correctly
      sliderInput("start_age", "Age of an individual at start of simulation", step = 1, value = 38, min = 18, max = 60),
      # This can be fixed as there are some hard checks in the model
      numericInput("time_horizon", "Max age in the model (100)", value = 100, min = 100),
      sliderInput("discount_health", "Health discount rate", step = 0.005, value = 0.035, min = 0, max = 0.06),
      sliderInput("discount_cost", "Cost discount rate", step = 0.005, value = 0.035, min = 0, max = 0.06),
      sliderInput("screen_startage", "Screen start age", value = 50, min = 18, max = 60),
      sliderInput("screen_endage", "Screen end age", value = 70, min = 18, max = 80)
    ),
    tabPanel(title = "Uptake",
      h3("NA"),
      sliderInput("uptakefirstscreen", "Probability that woman attends first screening", step = 0.01, value = 0.6, min = 0, max = 1),
      sliderInput("uptakeotherscreen", "Probability that woman attends further screening (having attended first)", step = 0.01, value = 0.85, min = 0, max = 1),
      sliderInput("uptakenoscreen", "Probability that woman attends screening (having missed first)", step = 0.01, value = 0.19, min = 0, max = 0.8),
      sliderInput("risk_uptake", "Proportion of women who want risk predicted", step = 0.01, value = 1, min = 0, max = 1),
      sliderInput("risk_feedback", "Proportion of women who attend risk consultation", step = 0.01, value = 1, min = 0, max = 1),
      sliderInput("screen_change", "Proportion of women with high/moderate/low risk who change screening interval", step = 0.01, value = 1, min = 0, max = 1)
    ),
    tabPanel(title = "Mortality",
      h3("Cancer and all cause mortality"),
      # Must be decreasing, adjust units (5-yr to rate param)
      sliderInput("gamma_survival_1", "Five-year survival for stage 1 cancer", step = 0.01, value = 0.98, min = 0, max = 1),
      sliderInput("gamma_survival_2", "Five-year survival for stage 2 cancer", step = 0.01, value = 0.9, min = 0, max = 1),
      sliderInput("gamma_survival_3", "Five-year survival for stage 3 cancer", step = 0.01, value = 0.72, min = 0, max = 1),
      # Must be decreasing, adjust units  (5-yr to rate param)
      sliderInput("meta_survival_54", "Five-year metatstatic survival, ages 0-54", step = 0.01, value = 0.43, min = 0, max = 1),
      sliderInput("meta_survival_74", "Five-year metastatic survival, ages 55-74", step = 0.01, value = 0.29, min = 0, max = 1),
      sliderInput("meta_survival_99", "Five-year metastatic survival, ages 75+", step = 0.01, value = 0.16, min = 0, max = 1),
      numericInput("acmmortality_wb_a", "All-cause mortality Weibull shape", value = 7.937),
      numericInput("acmmortality_wb_b", "All-cause mortality Weibull scale", value = 86.79),
      # Must sum to 1
      textInput("Incidence_Mortality","Incidence disribution")
    ),
    tabPanel(title = "Cancer Growth",
      h3("Cancer growth and staging"),
      # Fixed
      textInput("risk_mat","Synthetic dataset of breast density, 10 year, and lifetime breast cancer risk derived from PROCAS2 study"),
      shinyMatrix::matrixInput("metastatic_prob", value = data.matrix(data.frame(age=c(25,35,45,55,65,75,85), prob=c(0.046218154,0.086659039,0.109768116,0.127099924,0.142505975,0.159837783,1.73E-01)),rownames.force=F),
                               rows = list(names = F, editableNames = F),
                               cols = list(names = T, editableNames = F),
                               class = "numeric"),
      # This is quite an important one but there is quite complex calculation underpinning it that might need people to send me data to reformat
      shinyMatrix::matrixInput("stage_by_size_mat", value = data.matrix(data.frame(v1=c(0.383,0.567,0.611,0.557,0,0), v2=c(0.033,0.111,0.180,0.208,0.723,0.563), v3=c(0.058,0.057,0.208,0.147,0.206,0.351), v5=c(0.525,0.265,0.120,0.088,0.071,0.086)),rownames.force=F),
                               rows = list(names = F, editableNames = F),
                               cols = list(names = T, editableNames = F),
                               class = "numeric"),
      numericInput("screen_detection_m", "Mean doubling rate for tumours at screen detection", value = 6.12, min = 4, max = 8),
      numericInput("screen_detection_sd", "Standard deviation of the doubling rate for tumours at screen detection", value = 0.96),
      numericInput("clin_detection_m", "Mean doubling rate for tumours", value = 6.5, min = 4, max = 8),
      numericInput("clin_detection_sd", "Standard deviation of the doubling rate for tumours", value = 0.535),
      sliderInput("log_norm_mean", "Tumour growth rate mean (lognormal) (\u03b1\u2081) [1/yr]", value = 1.07, min = 0.1, max = 1.399),
      sliderInput("log_norm_sd", "Tumour growth rate SD (\u03b1\u2082) [1/yr]", value = 1.31, min = 0.1, max = 1.7),
      # Fixed
      numericInput("max_size", "Maximum tumour size [mm]", value = 128),
      # Fixed
      numericInput("start_size", "Tumour starting size (diameter) [mm]", value = 0.25)
      # UNKNOWN: NA
    ),
    tabPanel(title = "Screening",
      h3("Screening Performance"),
      sliderInput("prop_screen_detected", "Proportion of cancers in screening age range detected by screen", step = 0.01, value = 0.43, min = 0, max = 0.6),
      sliderInput("beta_1", "Sensitivity of mammography (\u03b2\u2081) [mm] \u2014 how rapidly sensitivity changes with tumour size", value = 1.47, min = 0.1, max = 1.8),
      sliderInput("beta_2", "Sensitivity of mammography (\u03b2\u2082) [mm] \u2014 size of tumour for which sensitivity is equal to 50%.", value = 6.51, min = 0.1, max = 8),
      # Fixed
      numericInput("sensitivity_max", "Maximum screening sensitivity", value = 0.95, min = 0, max = 1),
      # Sen_VDG must be decreasing, and less than sensitivity_max
      sliderInput("VDG1_sen", "Sensitivity of mammography for Volpara Density Group (VDG) 1.", step = 0.01, value = 0.85, min = 0, max = 1),
      sliderInput("VDG2_sen", "Sensitivity of mammography for Volpara Density Group (VDG) 2.", step = 0.01, value = 0.78, min = 0, max = 1),
      sliderInput("VDG3_sen", "Sensitivity of mammography for Volpara Density Group (VDG) 3.", step = 0.01, value = 0.7, min = 0, max = 1),
      sliderInput("VDG4_sen", "Sensitivity of mammography for Volpara Density Group (VDG) 4.", step = 0.01, value = 0.61, min = 0, max = 1),
      numericInput("Sen_VDG_av", "Average mammography sensitivity", value = 0.757),
      numericInput("Mammo_cdr", "Cancer detection rate [\u2030] high dense screens Mammo CEPAC", step = 0.1, value = 4.2, min = 1, max = 10),
      sliderInput("MRI_cdr", "Cancer Detection Rate for MRI in Mammo negative women [\u2030]", step = 0.1, value = 5, min = 1, max = 10),
      sliderInput("US_cdr", "Cancer Detection Rate for US in Mammo negative women [\u2030]", step = 0.1, value = 3, min = 1, max = 10),
      # UNKNOWN: NA
      # UNKNOWN: NA
      numericInput("low_risk_cut", "Risk cut-off in low-risk-only strategies", value = 1.5),
      numericInput("density_cutoff", "Breast density cut-offs for supplemental sreening (VDG groups 3 and 4)", value = 3, min = 1, max = 4)
    ),
    tabPanel(title = "Overdiagnosis",
      h3("False Positive and Overdiagnosis parameters"),
      numericInput("recall_rate", "Approx. UK recall rate", step = 0.01, value = 0.05, min = 0, max = 1),
      numericInput("biopsy_rate", "False-positive biopsy proportion", step = 0.01, value = 0.02, min = 0, max = 1)
    ),
    tabPanel(title = "Cost",
      h3("Cost data"),
      sliderInput("cost_strat", "Cost of stratification process [GBP]", value = 8.45, min = 0, max = 200),
      sliderInput("costscreen", "Cost of screening [GBP]", value = 60.56, min = 0, max = 200),
      sliderInput("cost_follow_up", "Cost of follow up [GBP]", value = 106, min = 0, max = 500),
      sliderInput("cost_biop", "Cost of biopsy [GBP]", value = 290, min = 0, max = 1000),
      numericInput("cost_DCIS", "Cost of treating ductal carcinoma in situ [GBP]", value = 9840, min = 0, max = 50000),
      sliderInput("cost_US", "Cost of ultrasonography [GBP]", value = 52, min = 0, max = 200),
      sliderInput("cost_MRI", "Cost of MRI [GBP]", value = 114, min = 0, max = 500),
      # Fixed (for now), to be simplified / tuned by simpler parameter set in the future
      shinyMatrix::matrixInput("tblLookup", value = data.matrix(costs_laudicella(),rownames.force=F),
                               rows = list(names = F, editableNames = F),
                               cols = list(names = T, editableNames = F),
                               class = "numeric"),
      sliderInput("costvar", "Multiplier for Cost of Cancer treatment", value = 1, min = 0.1, max = 10)
    ),
    tabPanel(title = "Utility",
      h3("Utility Weights"),
      shinyMatrix::matrixInput("utility_ages", value = data.matrix(data.frame(age=c(30,35,40,45,50,55,60,65,70,75,80,85,90,95,100), util=c(0.9383,0.9145,0.9069,0.8824,0.8639,0.8344,0.8222,0.8072,0.8041,0.779,0.7533,0.6985,0.6497,0.6497,0.6497)),rownames.force=F),
                               rows = list(names = F, editableNames = F),
                               cols = list(names = T, editableNames = F),
                               class = "numeric"),
      numericInput("utility_DCIS", "Non/micro-invasive tumour (DCIS) utility decrement", step = 0.01, value = 1, min = 0, max = 1),
      sliderInput("util_1to3", "Utility decrement (first yeara, set time independent) stages 1 to 3", step = 0.01, value = 0.82, min = 0, max = 1),
      sliderInput("util_4", "Utility decrement (first year, set time independent) metastatic", step = 0.01, value = 0.75, min = 0, max = 1),
      textInput("utility_stage_cat_y1","First year utility decrements (set time independent)"),
      textInput("utility_stage_cat_follow","Following year utility decrements (set time independent)")
    ),
  )
}
