# Documentation for data files


#' Monte Carlo runs used for Sensitivity Analysis and GAM model training.
#'
#' Columns represent input parameter variations for which a model has been
#' or is to be run. Currently generated by `draw_psa_runs`.
#'
#' Names are expected to match `input_list("basic")`. The table is used to set
#' soft bounds on basic inputs.
#'
#' @format  A data frame with one column per PSA parameter, and one row per MC draw.
#' @source `draw_psa_runs`
"PSA_config"

#' Model input configuration table
#'
#' Defines (dynamic) input types, limits, description, etc. generated by
#' "data-raw/parse_ui_table.R" and modified by "data-raw/load_soft_bounds.R"
#'
#' @format  A data frame with one row per model input.
#' \describe{
#'   \item{group}{defines tab/section where input is placed}
#'   \item{id}{unique input identifyer}
#'   \item{description}{ input description }
#'   \item{default}{ default value }
#'   \item{type}{"numeric", "slider", "checkbox", "text", "matrix", ... }
#'   \item{basic}{ boolean, is the input included in GAM model?}
#'   \item{fixed}{ boolean, should the input be available for advanced users?}
#'   \item{rel_min}{ soft minimum (set by `load_soft_bounds`) }
#'   \item{rel_max}{ soft maximum (set by `load_soft_bounds`) }
#'   \item{abs_min}{ hard minimum (read from `input_config.csv`) }
#'   \item{abs_max}{ hard maximum (read from `input_config.csv`) }
#'   \item{step}{ used for numeric & slider inputs }
#'   \item{unit}{ used to allow conversion between PSA variables and UI fields, see `utils.R/parse_units` }
#'   \item{notes}{ currently unused }
#'   \item{valid}{ boolean, has the input row been parsed successfully?}
#'   ...
#' }
#' @source "data-raw/parse_ui_table.R", "data-raw/load_soft_bounds.R"
"input_config_table"

#' Fitted GAM object for Qualy's
#'
#' @format  An object generated by mgcv::bam
#' @source ??
"qualy_model_obj"

#' Fitted GAM object for Costs
#'
#' @format  An object generated by mgcv::bam
#' @source ??
"cost_model_obj"

